/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as LayoutUsersRouteImport } from './routes/_layout/users'
import { Route as LayoutRolesRouteImport } from './routes/_layout/roles'
import { Route as LayoutSalesIndexRouteImport } from './routes/_layout/sales/index'
import { Route as LayoutPurchasesIndexRouteImport } from './routes/_layout/purchases/index'
import { Route as LayoutStoreSuppliersRouteImport } from './routes/_layout/store/suppliers'
import { Route as LayoutStoreProductsRouteImport } from './routes/_layout/store/products'
import { Route as LayoutStoreCategoriesRouteImport } from './routes/_layout/store/categories'
import { Route as LayoutSalesNewRouteImport } from './routes/_layout/sales/new'
import { Route as LayoutSalesDeliveryRouteImport } from './routes/_layout/sales/delivery'
import { Route as LayoutPurchasesNewRouteImport } from './routes/_layout/purchases/new'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutUsersRoute = LayoutUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutRolesRoute = LayoutRolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSalesIndexRoute = LayoutSalesIndexRouteImport.update({
  id: '/sales/',
  path: '/sales/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutPurchasesIndexRoute = LayoutPurchasesIndexRouteImport.update({
  id: '/purchases/',
  path: '/purchases/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutStoreSuppliersRoute = LayoutStoreSuppliersRouteImport.update({
  id: '/store/suppliers',
  path: '/store/suppliers',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutStoreProductsRoute = LayoutStoreProductsRouteImport.update({
  id: '/store/products',
  path: '/store/products',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutStoreCategoriesRoute = LayoutStoreCategoriesRouteImport.update({
  id: '/store/categories',
  path: '/store/categories',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSalesNewRoute = LayoutSalesNewRouteImport.update({
  id: '/sales/new',
  path: '/sales/new',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSalesDeliveryRoute = LayoutSalesDeliveryRouteImport.update({
  id: '/sales/delivery',
  path: '/sales/delivery',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutPurchasesNewRoute = LayoutPurchasesNewRouteImport.update({
  id: '/purchases/new',
  path: '/purchases/new',
  getParentRoute: () => LayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/login': typeof LoginRoute
  '/roles': typeof LayoutRolesRoute
  '/users': typeof LayoutUsersRoute
  '/': typeof LayoutIndexRoute
  '/purchases/new': typeof LayoutPurchasesNewRoute
  '/sales/delivery': typeof LayoutSalesDeliveryRoute
  '/sales/new': typeof LayoutSalesNewRoute
  '/store/categories': typeof LayoutStoreCategoriesRoute
  '/store/products': typeof LayoutStoreProductsRoute
  '/store/suppliers': typeof LayoutStoreSuppliersRoute
  '/purchases': typeof LayoutPurchasesIndexRoute
  '/sales': typeof LayoutSalesIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/roles': typeof LayoutRolesRoute
  '/users': typeof LayoutUsersRoute
  '/': typeof LayoutIndexRoute
  '/purchases/new': typeof LayoutPurchasesNewRoute
  '/sales/delivery': typeof LayoutSalesDeliveryRoute
  '/sales/new': typeof LayoutSalesNewRoute
  '/store/categories': typeof LayoutStoreCategoriesRoute
  '/store/products': typeof LayoutStoreProductsRoute
  '/store/suppliers': typeof LayoutStoreSuppliersRoute
  '/purchases': typeof LayoutPurchasesIndexRoute
  '/sales': typeof LayoutSalesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/login': typeof LoginRoute
  '/_layout/roles': typeof LayoutRolesRoute
  '/_layout/users': typeof LayoutUsersRoute
  '/_layout/': typeof LayoutIndexRoute
  '/_layout/purchases/new': typeof LayoutPurchasesNewRoute
  '/_layout/sales/delivery': typeof LayoutSalesDeliveryRoute
  '/_layout/sales/new': typeof LayoutSalesNewRoute
  '/_layout/store/categories': typeof LayoutStoreCategoriesRoute
  '/_layout/store/products': typeof LayoutStoreProductsRoute
  '/_layout/store/suppliers': typeof LayoutStoreSuppliersRoute
  '/_layout/purchases/': typeof LayoutPurchasesIndexRoute
  '/_layout/sales/': typeof LayoutSalesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/login'
    | '/roles'
    | '/users'
    | '/'
    | '/purchases/new'
    | '/sales/delivery'
    | '/sales/new'
    | '/store/categories'
    | '/store/products'
    | '/store/suppliers'
    | '/purchases'
    | '/sales'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/roles'
    | '/users'
    | '/'
    | '/purchases/new'
    | '/sales/delivery'
    | '/sales/new'
    | '/store/categories'
    | '/store/products'
    | '/store/suppliers'
    | '/purchases'
    | '/sales'
  id:
    | '__root__'
    | '/_layout'
    | '/login'
    | '/_layout/roles'
    | '/_layout/users'
    | '/_layout/'
    | '/_layout/purchases/new'
    | '/_layout/sales/delivery'
    | '/_layout/sales/new'
    | '/_layout/store/categories'
    | '/_layout/store/products'
    | '/_layout/store/suppliers'
    | '/_layout/purchases/'
    | '/_layout/sales/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/users': {
      id: '/_layout/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof LayoutUsersRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/roles': {
      id: '/_layout/roles'
      path: '/roles'
      fullPath: '/roles'
      preLoaderRoute: typeof LayoutRolesRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/sales/': {
      id: '/_layout/sales/'
      path: '/sales'
      fullPath: '/sales'
      preLoaderRoute: typeof LayoutSalesIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/purchases/': {
      id: '/_layout/purchases/'
      path: '/purchases'
      fullPath: '/purchases'
      preLoaderRoute: typeof LayoutPurchasesIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/store/suppliers': {
      id: '/_layout/store/suppliers'
      path: '/store/suppliers'
      fullPath: '/store/suppliers'
      preLoaderRoute: typeof LayoutStoreSuppliersRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/store/products': {
      id: '/_layout/store/products'
      path: '/store/products'
      fullPath: '/store/products'
      preLoaderRoute: typeof LayoutStoreProductsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/store/categories': {
      id: '/_layout/store/categories'
      path: '/store/categories'
      fullPath: '/store/categories'
      preLoaderRoute: typeof LayoutStoreCategoriesRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/sales/new': {
      id: '/_layout/sales/new'
      path: '/sales/new'
      fullPath: '/sales/new'
      preLoaderRoute: typeof LayoutSalesNewRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/sales/delivery': {
      id: '/_layout/sales/delivery'
      path: '/sales/delivery'
      fullPath: '/sales/delivery'
      preLoaderRoute: typeof LayoutSalesDeliveryRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/purchases/new': {
      id: '/_layout/purchases/new'
      path: '/purchases/new'
      fullPath: '/purchases/new'
      preLoaderRoute: typeof LayoutPurchasesNewRouteImport
      parentRoute: typeof LayoutRoute
    }
  }
}

interface LayoutRouteChildren {
  LayoutRolesRoute: typeof LayoutRolesRoute
  LayoutUsersRoute: typeof LayoutUsersRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
  LayoutPurchasesNewRoute: typeof LayoutPurchasesNewRoute
  LayoutSalesDeliveryRoute: typeof LayoutSalesDeliveryRoute
  LayoutSalesNewRoute: typeof LayoutSalesNewRoute
  LayoutStoreCategoriesRoute: typeof LayoutStoreCategoriesRoute
  LayoutStoreProductsRoute: typeof LayoutStoreProductsRoute
  LayoutStoreSuppliersRoute: typeof LayoutStoreSuppliersRoute
  LayoutPurchasesIndexRoute: typeof LayoutPurchasesIndexRoute
  LayoutSalesIndexRoute: typeof LayoutSalesIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutRolesRoute: LayoutRolesRoute,
  LayoutUsersRoute: LayoutUsersRoute,
  LayoutIndexRoute: LayoutIndexRoute,
  LayoutPurchasesNewRoute: LayoutPurchasesNewRoute,
  LayoutSalesDeliveryRoute: LayoutSalesDeliveryRoute,
  LayoutSalesNewRoute: LayoutSalesNewRoute,
  LayoutStoreCategoriesRoute: LayoutStoreCategoriesRoute,
  LayoutStoreProductsRoute: LayoutStoreProductsRoute,
  LayoutStoreSuppliersRoute: LayoutStoreSuppliersRoute,
  LayoutPurchasesIndexRoute: LayoutPurchasesIndexRoute,
  LayoutSalesIndexRoute: LayoutSalesIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
