export const products = [
  {
    name: "Paracetamol 500mg",
    description:
      "Analgésico y antipirético utilizado para aliviar dolores leves y reducir fiebre.",
    salePrice: 3.5,
    purchasePrice: 2.0,
    stockQuantity: 120,
    imageUrl: "https://res.cloudinary.com/dxttebpgo/image/upload/f_auto,q_auto/v1/pharmacy/l9vdmajhf9vbrokbtr9y",
    categoryId: 1,
    supplierId: 1,
  },
  {
    name: "Vitamina C 1000mg",
    description:
      "Suplemento vitamínico que ayuda a fortalecer el sistema inmunológico.",
    salePrice: 4.99,
    purchasePrice: 3.0,
    stockQuantity: 150,
    imageUrl: "https://res.cloudinary.com/dxttebpgo/image/upload/f_auto,q_auto/v1/pharmacy/tyqxib6rsqceb2qljkpk",
    categoryId: 2,
    supplierId: 2,
  },
  {
    name: "Multivitamínico",
    description: "Complejo vitamínico para complementar la dieta diaria.",
    salePrice: 15.0,
    purchasePrice: 10.0,
    stockQuantity: 100,
    imageUrl: "https://res.cloudinary.com/dxttebpgo/image/upload/f_auto,q_auto/v1/pharmacy/xm1yj5ramht012bdaur4",
    categoryId: 2,
    supplierId: 3,
  },
  {
    name: "Shampoo Anticaspa",
    description:
      "Shampoo para el control de la caspa y cuidado del cuero cabelludo.",
    salePrice: 5.99,
    purchasePrice: 4.0,
    stockQuantity: 75,
    imageUrl: "https://res.cloudinary.com/dxttebpgo/image/upload/f_auto,q_auto/v1/pharmacy/lm90o5bq2pl7u8iakwzd",
    categoryId: 3,
    supplierId: 3,
  },
  {
    name: "Crema Hidratante",
    description: "Crema para la hidratación profunda de la piel.",
    salePrice: 12.0,
    purchasePrice: 7.5,
    stockQuantity: 50,
    imageUrl: "https://res.cloudinary.com/dxttebpgo/image/upload/f_auto,q_auto/v1/pharmacy/ldhyl77nhgek1tqyssv8",
    categoryId: 4,
    supplierId: 4,
  },
  {
    name: "Termómetro Digital",
    description:
      "Termómetro digital de fácil lectura para medir la temperatura corporal.",
    salePrice: 15.0,
    purchasePrice: 10.0,
    stockQuantity: 30,
    imageUrl: "https://res.cloudinary.com/dxttebpgo/image/upload/v1732052221/pharmacy/z1mjszz4oxuw1fqstk66.png",
    categoryId: 5,
    supplierId: 5,
  },
  {
    name: "Ibuprofeno 400mg",
    description:
      "Anti-inflamatorio no esteroideo utilizado para reducir la fiebre, el dolor y la inflamación.",
    salePrice: 4.0,
    purchasePrice: 2.5,
    stockQuantity: 90,
    imageUrl: "https://res.cloudinary.com/dxttebpgo/image/upload/f_auto,q_auto/v1/pharmacy/r15rk4nssihi7neaavp6",
    categoryId: 1,
    supplierId: 1,
  },
  {
    name: "Amoxicilina 500mg",
    description: "Antibiótico de amplio espectro para infecciones bacterianas.",
    salePrice: 8.5,
    purchasePrice: 5.0,
    stockQuantity: 80,
    imageUrl: "https://res.cloudinary.com/dxttebpgo/image/upload/f_auto,q_auto/v1/pharmacy/o0gr65bqsma4gasnibm6",
    categoryId: 1,
    supplierId: 3,
  },
  {
    name: "Lorazepam 2mg",
    description: "Ansiolítico utilizado para el tratamiento de ansiedad.",
    salePrice: 12.0,
    purchasePrice: 7.0,
    stockQuantity: 50,
    imageUrl: "https://res.cloudinary.com/dxttebpgo/image/upload/f_auto,q_auto/v1/pharmacy/ndl7211mu5vgekdc84of",
    categoryId: 1,
    supplierId: 1,
  },
  {
    name: "Omega 3 1000mg",
    description: "Suplemento que favorece la salud cardiovascular y cerebral.",
    salePrice: 8.0,
    purchasePrice: 5.0,
    stockQuantity: 110,
    imageUrl: "https://res.cloudinary.com/dxttebpgo/image/upload/f_auto,q_auto/v1/pharmacy/tzvjoqniao9zsx9oier0",
    categoryId: 2,
    supplierId: 2,
  },
  {
    name: "Jabón Líquido Antibacterial",
    description:
      "Jabón líquido para la higiene de manos, con propiedades antibacterianas.",
    salePrice: 3.0,
    purchasePrice: 1.8,
    stockQuantity: 200,
    imageUrl: "https://res.cloudinary.com/dxttebpgo/image/upload/f_auto,q_auto/v1/pharmacy/webqqfyepqugpxcdzep3",
    categoryId: 3,
    supplierId: 3,
  },
  {
    name: "Maquillaje Base Líquido",
    description:
      "Base líquida para maquillaje, ideal para una cobertura ligera y natural.",
    salePrice: 10.0,
    purchasePrice: 6.0,
    stockQuantity: 60,
    imageUrl: "https://res.cloudinary.com/dxttebpgo/image/upload/f_auto,q_auto/v1/pharmacy/y0jeja1dzoido2hj91h4",
    categoryId: 4,
    supplierId: 4,
  },
  {
    name: "Oxímetro de Pulso",
    description:
      "Dispositivo portátil para medir la saturación de oxígeno en sangre y la frecuencia cardíaca.",
    salePrice: 25.0,
    purchasePrice: 15.0,
    stockQuantity: 40,
    imageUrl: "https://res.cloudinary.com/dxttebpgo/image/upload/f_auto,q_auto/v1/pharmacy/j0oqgzyylwagrdf47jxi",
    categoryId: 5,
    supplierId: 5,
  },
  {
    name: "Pasta Dental Fluorada",
    description: "Protección contra caries y limpieza dental avanzada.",
    salePrice: 3.0,
    purchasePrice: 1.8,
    stockQuantity: 300,
    imageUrl: "https://res.cloudinary.com/dxttebpgo/image/upload/f_auto,q_auto/v1/pharmacy/vjglbtlgo4bwiiurzqg5",
    categoryId: 3,
    supplierId: 5,
  },
  {
    name: "Jabón Antibacterial",
    description: "Elimina bacterias y cuida la piel.",
    salePrice: 2.5,
    purchasePrice: 1.5,
    stockQuantity: 400,
    imageUrl: "https://res.cloudinary.com/dxttebpgo/image/upload/f_auto,q_auto/v1/pharmacy/noq9ws0qvyzandnuek6o",
    categoryId: 3,
    supplierId: 2,
  },
  {
    name: "Shampoo Hidratante",
    description: "Hidratación profunda para cabello seco.",
    salePrice: 6.5,
    purchasePrice: 4.0,
    stockQuantity: 180,
    imageUrl: "https://res.cloudinary.com/dxttebpgo/image/upload/v1732052730/pharmacy/cubkn2i5o5xdvl8rgg9p.png",
    categoryId: 3,
    supplierId: 4,
  },
  {
    name: "Crema Hidratante Facial",
    description: "Hidratación diaria para una piel suave y saludable.",
    salePrice: 12.0,
    purchasePrice: 8.0,
    stockQuantity: 90,
    imageUrl: "https://res.cloudinary.com/dxttebpgo/image/upload/f_auto,q_auto/v1/pharmacy/vh5dztbw39z42kydjaie",
    categoryId: 4,
    supplierId: 3,
  },
  {
    name: "Lápiz Labial Mate",
    description: "Larga duración y colores intensos.",
    salePrice: 7.0,
    purchasePrice: 4.5,
    stockQuantity: 70,
    imageUrl: "https://res.cloudinary.com/dxttebpgo/image/upload/f_auto,q_auto/v1/pharmacy/yepyosnbwj51edxk5u5v",
    categoryId: 4,
    supplierId: 5,
  },
  {
    name: "Protector Solar SPF 50",
    description: "Protección contra rayos UVA y UVB.",
    salePrice: 10.0,
    purchasePrice: 6.0,
    stockQuantity: 120,
    imageUrl: "https://res.cloudinary.com/dxttebpgo/image/upload/f_auto,q_auto/v1/pharmacy/q5kpdrzof5whv4evmiel",
    categoryId: 4,
    supplierId: 2,
  },
  {
    name: "Tensiómetro Automático",
    description: "Monitoreo de la presión arterial en casa.",
    salePrice: 50.0,
    purchasePrice: 35.0,
    stockQuantity: 30,
    imageUrl: "https://res.cloudinary.com/dxttebpgo/image/upload/f_auto,q_auto/v1/pharmacy/hlfc2kfvmbkid5wygy2t",
    categoryId: 5,
    supplierId: 4,
  },
];
