export const products = [
  {
    name: "Paracetamol 500mg",
    description:
      "Analgésico y antipirético utilizado para aliviar dolores leves y reducir fiebre.",
    salePrice: 3.5,
    purchasePrice: 2.0,
    stockQuantity: 120,
    categoryId: 1,
    supplierId: 1,
  },
  {
    name: "Vitamina C 1000mg",
    description:
      "Suplemento vitamínico que ayuda a fortalecer el sistema inmunológico.",
    salePrice: 5.0,
    purchasePrice: 3.0,
    stockQuantity: 150,
    categoryId: 2,
    supplierId: 2,
  },
  {
    name: "Multivitamínico",
    description: "Complejo vitamínico para complementar la dieta diaria.",
    salePrice: 15.0,
    purchasePrice: 10.0,
    stockQuantity: 100,
    categoryId: 2,
    supplierId: 3,
  },
  {
    name: "Shampoo Anticaspa",
    description:
      "Shampoo para el control de la caspa y cuidado del cuero cabelludo.",
    salePrice: 6.0,
    purchasePrice: 4.0,
    stockQuantity: 75,
    categoryId: 3,
    supplierId: 3,
  },
  {
    name: "Crema Hidratante",
    description: "Crema para la hidratación profunda de la piel.",
    salePrice: 12.0,
    purchasePrice: 7.5,
    stockQuantity: 50,
    categoryId: 4,
    supplierId: 4,
  },
  {
    name: "Termómetro Digital",
    description:
      "Termómetro digital de fácil lectura para medir la temperatura corporal.",
    salePrice: 15.0,
    purchasePrice: 10.0,
    stockQuantity: 30,
    categoryId: 5,
    supplierId: 5,
  },
  {
    name: "Ibuprofeno 400mg",
    description:
      "Anti-inflamatorio no esteroideo utilizado para reducir la fiebre, el dolor y la inflamación.",
    salePrice: 4.0,
    purchasePrice: 2.5,
    stockQuantity: 90,
    categoryId: 1,
    supplierId: 1,
  },
  {
    name: "Amoxicilina 500mg",
    description: "Antibiótico de amplio espectro para infecciones bacterianas.",
    salePrice: 8.5,
    purchasePrice: 5.0,
    stockQuantity: 80,
    categoryId: 1,
    supplierId: 3,
  },
  {
    name: "Lorazepam 2mg",
    description: "Ansiolítico utilizado para el tratamiento de ansiedad.",
    salePrice: 12.0,
    purchasePrice: 7.0,
    stockQuantity: 50,
    categoryId: 1,
    supplierId: 1,
  },
  {
    name: "Omega 3 1000mg",
    description: "Suplemento que favorece la salud cardiovascular y cerebral.",
    salePrice: 8.0,
    purchasePrice: 5.0,
    stockQuantity: 110,
    categoryId: 2,
    supplierId: 2,
  },
  {
    name: "Jabón Líquido Antibacterial",
    description:
      "Jabón líquido para la higiene de manos, con propiedades antibacterianas.",
    salePrice: 3.0,
    purchasePrice: 1.8,
    stockQuantity: 200,
    categoryId: 3,
    supplierId: 3,
  },
  {
    name: "Maquillaje Base Líquido",
    description:
      "Base líquida para maquillaje, ideal para una cobertura ligera y natural.",
    salePrice: 10.0,
    purchasePrice: 6.0,
    stockQuantity: 60,
    categoryId: 4,
    supplierId: 4,
  },
  {
    name: "Oxímetro de Pulso",
    description:
      "Dispositivo portátil para medir la saturación de oxígeno en sangre y la frecuencia cardíaca.",
    salePrice: 25.0,
    purchasePrice: 15.0,
    stockQuantity: 40,
    categoryId: 5,
    supplierId: 5,
  },
  {
    name: "Pasta Dental Fluorada",
    description: "Protección contra caries y limpieza dental avanzada.",
    salePrice: 3.0,
    purchasePrice: 1.8,
    stockQuantity: 300,
    categoryId: 3,
    supplierId: 5,
  },
  {
    name: "Jabón Antibacterial",
    description: "Elimina bacterias y cuida la piel.",
    salePrice: 2.5,
    purchasePrice: 1.5,
    stockQuantity: 400,
    categoryId: 3,
    supplierId: 2,
  },
  {
    name: "Shampoo Hidratante",
    description: "Hidratación profunda para cabello seco.",
    salePrice: 6.5,
    purchasePrice: 4.0,
    stockQuantity: 180,
    categoryId: 3,
    supplierId: 4,
  },
  {
    name: "Crema Hidratante Facial",
    description: "Hidratación diaria para una piel suave y saludable.",
    salePrice: 12.0,
    purchasePrice: 8.0,
    stockQuantity: 90,
    categoryId: 4,
    supplierId: 3,
  },
  {
    name: "Lápiz Labial Mate",
    description: "Larga duración y colores intensos.",
    salePrice: 7.0,
    purchasePrice: 4.5,
    stockQuantity: 70,
    categoryId: 4,
    supplierId: 5,
  },
  {
    name: "Protector Solar SPF 50",
    description: "Protección contra rayos UVA y UVB.",
    salePrice: 10.0,
    purchasePrice: 6.0,
    stockQuantity: 120,
    categoryId: 4,
    supplierId: 2,
  },
  {
    name: "Tensiómetro Automático",
    description: "Monitoreo de la presión arterial en casa.",
    salePrice: 50.0,
    purchasePrice: 35.0,
    stockQuantity: 30,
    categoryId: 5,
    supplierId: 4,
  },
];
